# Generated by Django 5.1.5 on 2025-03-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
