services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop_admin
      - POSTGRES_PASSWORD=Nastya_03.04
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - store_project_network

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - store_project_network

networks:
  store_project_network:
    driver: bridge

volumes:
  pg_data:




